apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:abVLVffv/BzZllhjFrVGNJ4H1niqq9tAyxA0yJuQgveeZrjyQ1MtRw==,iv:99cngtM0GEHvof9aG4FlsO5m0vs5xGvafOpRwusVUN8=,tag:WRUhYvnc6mDOZgXaK+FGhQ==,type:str]
sops:
  age:
    - recipient: age1g5svy8c3sp3w9xqg7xrq8y3ckk36f7k59f0jgl8wx2vywqz7qpnqm8tsll
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwWjRTZFd3b2FGeDNyN3c0
        ZWxQaCsvTHZVSGZtb083R2NOZFdWcUFRN2dVCnF0TVJtY2hQdk1xRm9SYWFFSDJ3
        V0FkM3NvVHBnMmZxbjdyQUlkb3c0OU0KLS0tIGFIZWZwWWpYZ3RucmMxV0kvem1F
        WHZsRDgwYlluekV0UGtqc2ZSdWFQQmsKECifYyjoChMS6gj1pc5SGDKz6m/PirFf
        83+eyL5XpBjY8xRWrwZsdi9JL0/5R7H4oVDW9jM1zf9wmLuD/Z4T6A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-18T00:07:32Z"
  mac: ENC[AES256_GCM,data:XVW8akYXbhBj1zWjR9+nmmpVpd6fBHjY1yI88oDD6NTT9+l6959MlKoZht/mk58GqsOTs/tXq8Isnu1Dpr92Jm2115GQ1SyVKAeqpQVIthkpuKnYmQVSxEAthjKWSsaPN7ikjinhzSA0iNvT6fsKQ0y/KyltKiEnPuJfsOUTP4A=,iv:dLK3v6L1Mv2wjUgYZeKW5NWJoF1MD/TK3+lEFWkb92o=,tag:X5ddBMe+7tdx1NjEcuPcwQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
