apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:PbQQaegW9On2e0Vpj/qACV+mTfMW6jXEUDIRr25IHSV8gSVmZpsXPA==,iv:69fWRDGXSTyu3ePv62dqn2U0X3bLlx+23rZmGe/pNEE=,tag:Xzp9ERZ6ogrN0y+6rR6VdA==,type:str]
sops:
  age:
    - recipient: age1g5svy8c3sp3w9xqg7xrq8y3ckk36f7k59f0jgl8wx2vywqz7qpnqm8tsll
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpdzV4MjZ5ankwRG95cncy
        a01OSjJRbVZ6dTVJS2VvZEU5OWxHOEFab2tvCmFKZmgrSktXUW12dklBMDg4Zkxk
        d09JNXBGR3BRT2tMc1AzTTdIbE1JR00KLS0tIHJVZXE5dzNCYm0yaVFKaXMzd1Q5
        VldabTZEQXF5NHRMaFNXb3pVRENIQ2MK45pO/1KAxLBLPCHKEUbkNHHy2PRFmm18
        P8LwrVJpIGJzPWBk41NTZTt0RUg/2+DsLahaUb94f1s6fH0X35IDdw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-17T23:16:32Z"
  mac: ENC[AES256_GCM,data:WYgQbmNju1N6997VEgpgNQwcTtghym3mK4WrT2ugT8LIyY4lRuB+xuTseBQ2PJVsvxz38FqSEoGMxKKi49/OXZvIveGvuI7d4RQsWcMVDwy1q/PIPV+EDEopRuuts/emDhZmg6PZD4pgTM72b6IVmDowB32y0Qz2zWsf4e9HO3c=,iv:AY9agMQ1jZBTmm5mqdQaXfwWe15E/wKCpyG9JGYA3SM=,tag:/Kq9vaiZ/Orir+7n5VXvTw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
