apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:fqM7OXaCZaRSgb8ijY/t4+yFRO9O7Qi5gDhh1jacVdVMyQGPStKxqg==,iv:+3zMLsoUqGcTrmIKz3Bd3fh0eraXblbVJQLYZdd9ANE=,tag:8p/TAtcqaF9uNLVvEB+gaA==,type:str]
sops:
  age:
    - recipient: age1g5svy8c3sp3w9xqg7xrq8y3ckk36f7k59f0jgl8wx2vywqz7qpnqm8tsll
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZHR6bkR1UkpuOVMzS0ZN
        dS9HQ0VGd0k1N1dId2hIWEloalM3anBMbHdRCnlLV25mSXZUSWJ3Z3hYaTlmNDVk
        cTZoS1hxcmxCdThUUjNWdXo1N0k5VXcKLS0tIHJINHVldDNDalZiUkpHNSt4NFdH
        bkJqWG9IblFmdGt2UEV5RTY0WXhMa2MKawPFhTnXKXqGP5Lh20rXBoNIYP8lRLOE
        m3LEFQpvMLLrhgaXdwjecuMnDr3R8+OxNt6iEAjJlXUwYsic2DAkJA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-18T00:02:22Z"
  mac: ENC[AES256_GCM,data:V9zpt9nASS5d1sEDlH9Mmisnn24QmLN9Sum0im7N9kJuga5A+09FrB59QF/4f4kLDDPbaHx2hvP5Vu04NrubWKJbx+tf9diBtCb7M16JbinteXji+T0avsK3BIvhBgHo5vA2PmUcdb4jgJ11WpfO9ferRZlhDGSsVdZczTExwI4=,iv:VNhSvv3hsWaGcEqYcYnH2GnTWVEZi4FchsxGx1s5tnU=,tag:dSD14f0A87dGievxnrgszA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
