apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:ulU9Fa5RK3eUvwj1rA==,iv:3EWBTb17RF8gM3EZjb8KfolXh8JEWGqZjQQYLzPSN0I=,tag:nXT4+YKkMg+VfXqktglJ3Q==,type:str]
sops:
  age:
    - recipient: age1g5svy8c3sp3w9xqg7xrq8y3ckk36f7k59f0jgl8wx2vywqz7qpnqm8tsll
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdFgybEkrdHlFY3g3N2JN
        TnF3S2NQRytRTU9TVlB1b015emFoODhIVDFRClozRXZRWUs5U3B5YXVJaE9VM25Q
        RkQ3Y1lWRnlkNGhxMFM5ZmdDK1pPSTAKLS0tIFdCUXFWT3o2d1Mwai84WXlKdktU
        K0VFU2JaQzRERHRRbU5xamx4V1RWaXcKX+O5tbLE3dDLTGgoyggc4OQh6t+tbQ1M
        2IxjI/I9iXXWrmtlQGisL/w/LRbyw4f8s6YJil+1roT47lC1pvJcnw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-17T23:16:32Z"
  mac: ENC[AES256_GCM,data:8KbBgqLWaKEc3IX+XuHHRjSEtBDoXREPjVO4I7HxETIfzuAfUK12w7/K7aHZy4Ubf/YfsTmBEsfOPc8jjeY0o0ZLkgB7VYfTzvQzqLDuSvkLGJXiOdvYasP+BXfe71f6h28QSrHIzvWZ/TJFd/a5JZsMW/eCCmnNyTdUkcaTSDE=,iv:7mrbeaP2TetzBOaaU1wuA6Ih3KzBw6TwnyiBDFXrEgc=,tag:TiNf6y4AYMOmjKTelC6dvw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
