apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:o6FOm//9Zjq14WwUpg==,iv:YiFa1i1ylQ0/y8bhBIVuYvcTUr6+c2UprNGNewahjuU=,tag:WSR3Rx9wzVDLKWTg2egeHQ==,type:str]
sops:
  age:
    - recipient: age1g5svy8c3sp3w9xqg7xrq8y3ckk36f7k59f0jgl8wx2vywqz7qpnqm8tsll
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjMWxqeVBKZXhTVHlNU1lD
        VEZYd2JoZmE2d1dKeHdxOVVrbEF3WDRaSFZZCmZuMDE0clRPNk1jY2tFeURLV25x
        Y2UvUVY0Z2tFdmdZWitsclJvQ0xCZmcKLS0tIHZ2bnRQaUphVDNjSXZXaTd4K0Fw
        ZnFTSmdtR3lmWjNmb2M5ek0zeDBrbGcKpWuKpQEKh725cHlW48v+q9SZOoL+Jydy
        3gggrn3oqSdwQjCUetj/8gWD3oHw9Icvim9M7creBYzo/jfahkkDYQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-18T00:02:23Z"
  mac: ENC[AES256_GCM,data:3YzGwdokXF1lgzaKv1wYosMT9ds43lBRpIr6ttu1LTm1iksmiVNBRvHS9EUlVc/erN3MXFC1IytLiV6PY0iipqYu+IFzP+QzZcLPhqZuFrrTahGgO2IWOQnVaFxAlmCnZwLCxaY3LP+yfZ/tjuIm5T3J6mkIPo3K/F/rQkG40Qo=,iv:XZ/91j80Ik8IS1dBUPaxDKJqCtv4YQ0vvBguXU1ya74=,tag:82Hhp12vDi0cpqydTOSEQw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
