apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:EJpkVlyni84avYsncQ==,iv:9p+pT5D/TfQsMmJeQ61ALClKsiU4JalNQ+1qZW02UEk=,tag:ay/1nkas4D+lYEthtVwo2w==,type:str]
sops:
  age:
    - recipient: age1g5svy8c3sp3w9xqg7xrq8y3ckk36f7k59f0jgl8wx2vywqz7qpnqm8tsll
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRGdYVkJNenMxRENPUTc5
        N3gvMFhOSDd5MHEzbUVtNCs2K2FxcngrYzFrCnl1QzNmSDUxTG1WM01KdWM5dG1a
        Zzl2T2hhbjEzVUhaV1gyQ3VHYUlYS0EKLS0tIDIzN2YrNVhCT3ZNRDJBcGt1ZVB1
        V1FCV09xYTdxUDdGMFdJZTAwZzFIUTAKdRyPRHamy8DV5bxl61Rct4cSVpjs9mCi
        GRx63CPGjnQOQzRsfG7vnPuCA+tapT4hao+oWuCP71e0mzH7zbe6rA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-18T00:21:37Z"
  mac: ENC[AES256_GCM,data:XHsWqZBhzUUFx8yhTxGhQjnaOJxNhLehnI/XYyilnj2f+V7u9bWgkRYfnrHbvkNJYpyzMewNib6zwha/oLIWiZyVe0eCtF76SzQ+61yiodH4mXPeNL40+kIQpiT1A2xYzhV4eKAEMAtuizJqBk4wM330ohL3kxcgwyZ7Qcdbz0I=,iv:FXufNATdXVnOlQxCFvEMRX7lLC/tSbCBnazi3NOnj1Q=,tag:o/8h43PZGapnx3IT5QJhWQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
