apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:k3twI3wD8BaYHckv3F4zsnIgyqttN4D5rL2RqLmpe2A=,iv:OgVT42GjP7+FhgCIp39tSlLjk7F9PAzw7l3dqL6Moeo=,tag:BWWt6szOM/feMie85L9QaQ==,type:str]
sops:
  age:
    - recipient: age1g5svy8c3sp3w9xqg7xrq8y3ckk36f7k59f0jgl8wx2vywqz7qpnqm8tsll
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMNGJCSVdBUTFmTnNZVSsw
        S2RUWTFmbjNpY2JVVkR1UTdZTjlsUGhCK3kwCnJaNDJjVzZSK01FSHM3cGZOb282
        LzhmMjg4ZGgxTlpEdUc1V01rU1VQOEUKLS0tIElNN1R3eHVUdEFnZFZSanpLUVhP
        R3BGMGozenQ4bE5YY3o1SFFmcW5abDgKsNg9x/VGv1BndXFbR8axZaJjLTcchFWW
        GbKABvK+GfVso6k5ekV1rHIOkMpCXg7WG3ffmn0sLvsxwoV+8TYeig==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-18T00:02:22Z"
  mac: ENC[AES256_GCM,data:nM/Z90RdK71EXBripgv4wnkJUl3k6CUWSISK3TjtSuFZsVkc0vYQJOtK875ufd1ZiqVBlRlscdXNaniaFZlikqdYNe61cqi+Qk0/yhg3IXqGWiLctmrmGaCDDq90z1Ows2f3CKYfp7vysMY+CuxycRmu9TiIZQvEFbm5q6414JM=,iv:Y93lzWJKf3Llz59BC6ULjx22imSEVPUspZzAP8xJpNo=,tag:/yCKUtn+83PU9nNZO2vf+g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
