apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:EHSkxN8qJ1XNwryLrRjfxClM8deOA0VLc86qeNMSk5w=,iv:kwa9rpAKwrt4vUog1z2v407uN3q6gzABfz3w9DTY3Vo=,tag:vUuWWl3BW5fYTIZLToEr3Q==,type:str]
sops:
  age:
    - recipient: age1g5svy8c3sp3w9xqg7xrq8y3ckk36f7k59f0jgl8wx2vywqz7qpnqm8tsll
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1KzN5MmZXSElnZUZQRDlM
        ZVg2aHcyOU1VdlhuN0x0UDlFRFNlZVBrRkJzCjFUQ2FPZk9XcUNtZmRwZEwvOVIr
        TGRBbnN1azhIbHVnRHAwYXFDMVpoS0kKLS0tIGVPem1CZlphaW1LVkhUaGh5YnZx
        MSthbGxoM21rcGtiMmtWSzh5bzVUSGcKvFugGQYnG2EraOXTZYvAY+rc2eH49b3n
        5sKydCoGHTArKZk6OkW4B6K0X3gw+HNo96HGlEw87RMIyPiFWTDFtg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-18T00:07:32Z"
  mac: ENC[AES256_GCM,data:hR0IZ2+f2y+ADi1Pb1uaJuIw4v06vTUqsZd8PVuz91tuXXId7zgw103AH7rWnfDydpc1AwOzcAbSCoOXaSHv6fJAucE7ea0cWutp6tEtrXO4dS6TUC4eF0t3KKfaxDRqdAJ83+i/WaUefZB3G2H+8Wv3ePNuYgPPLXCsO9Lwyx4=,iv:6VrTkfLlpnroUW8kzxLde0F6uXI6bQavzHb9Xs+ertc=,tag:Gw9IJvXLfoFB0MJRGz0+wQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
