apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:wtuQLIhm+QS44XEL8ZQcqaHGWoqaDsMdDbWca3Y37uI=,iv:eQpPjRXHpQw8oTR1T20/cNUACZEb+mJD/LwGFXo13UY=,tag:ctJgta9zuNtiYYfQW0SK+g==,type:str]
sops:
  age:
    - recipient: age1g5svy8c3sp3w9xqg7xrq8y3ckk36f7k59f0jgl8wx2vywqz7qpnqm8tsll
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxQjZ5VEFRTWl2NWt1VzU3
        QnFoU2RxV2grRVdYZzdtOU5MWUw1czdrZzFJCkpJYUVqNW5aTlkxWGdkUStCY0lC
        WTd5QlI3SytPTjFjNVl0ems0UVIzVXcKLS0tIHVZTG5wZW5mRi8yMU55UFlGd3Bv
        dTJqZC9jL2VSY3QxT3dDb0NFMFJnSncKqi0UQaGuvHPXx88zjVHH+c0Fzqg5sMx1
        3oopMqHP1wQe9ko0GUqsHEPhcS8/OGtbLHmY5nkKETO9wmyXhRhD4A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-18T00:21:37Z"
  mac: ENC[AES256_GCM,data:lHxknHhpvVfQLMxKgqvnzd3Ic2RGz/dOY7MKLDNS2yIJA8uvRT4aRwLXIbSdjxtM+qJCOuOuj5D3D0IHFoYYHK9SmyrrTe0VZn3K471YFAlFAb4bZ+cYgANOr9Hr6vA3+l9RaZhD7m0aC0WJEj/Qz9qm9uosdOtkT+px88iCHsc=,iv:LZrc0XRI5UF9ivBG778LGIZ7WPzMcGExnzkks7Bo5XI=,tag:eXVNRaegA81zqVrBI0hv9g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
