apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:YmSgrMMZqUqEYCPUPUaKF3A2TXvBdUryr7jK1m+O/V6B3xmCmhXieDMBl/oRKRdvqEohBUQDJREZ0JLavMIqNHQkAZSNYOxpujquaPoBLymvZ2hm1rcG8rDxk3lblD1hU4zQR3umToukST3jHklnIwVpfE0qEO5y2Ikd5znR7IvBi8BPeYVGBydBUmr1alPlrcYLqxg96sWbw29dBczj9BniiTOs2+e41H2fhGVNJOR2Q9xx,iv:eIEptrw8xm1/fHOMv2tKcB0zvbrvpsfb+Rbjt1phy9E=,tag:278VifsGE6D8PsT65uAttg==,type:str]
sops:
  age:
    - recipient: age1g5svy8c3sp3w9xqg7xrq8y3ckk36f7k59f0jgl8wx2vywqz7qpnqm8tsll
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXRVdIMCtWU3gvVWN5TW90
        V1lGM2dzQktmamJ6MkhHd2F4bzJXd3dtK0VzClo0MjBDYkpXWHVybjdWa09BYXZa
        QlNyVWM2ZFBrRVpyOUxWOW5jaElycEUKLS0tIFpqakw5UkhNNSsweFQ2My9GSGR5
        L3B0WFlVYzc2TXhwTWZwRXEvNXBFd28Kxw5QKjbNOT+MKCEkv8VkmaWKzu6LBYTA
        X5fsZqB91AK29yJqy5Cv0BsroVbRcZ45IAjvZQ2iEdCI0yj7Sl6UrA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-18T00:02:23Z"
  mac: ENC[AES256_GCM,data:Zm0f1oaS3uBUdDtwC+E7KJSgz/GVGCuuJ/yjp3vT3qC1S3sXGk6F1y26kqbvpsKoH5AxOP9+pDWY7NAMzE3w2G1yJMM1aXbOWGxN4XIvpiPLfEjS5Z1G8Ndo9Nv0aRYGuisBGWgSK6CmWVpa9G/808AUJTDUzcUu44INc0NzIJQ=,iv:4LymUyf6u9bIp76W+TxUUX8RWDCSH8TRo5Kn1APNvmE=,tag:XbDWm9Yk5LEsKehztoOMeg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
