apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:Obmfb8NQv6tBCEH6vWXZ2mZXOtZMMF200gTe2xuyt9o9BH1Ym0yWqH7Le4qMAGJgoPniZfWUSAG2MNBR/58Fzu3L4KSAVN5LuzL/77dJ2CjgSKCOFsmuGEWmavhzfbqSmDxq9JJzfGmWjkeawUxRSpj0GVz03JfKiMKVKqcXx2bN10ifFZFdUJL1SdcVFs3+39fKSC3Han0H95rQKtKMpMSkpEqmZrOiUvXYoa7naU8g8cIB,iv:1Z0ANdyhFYH6bIRCPlVE3OjtOgknx7Dvt2HupNaYT88=,tag:BxGIkzpuwn/Ok0ozOaLGPA==,type:str]
sops:
  age:
    - recipient: age1g5svy8c3sp3w9xqg7xrq8y3ckk36f7k59f0jgl8wx2vywqz7qpnqm8tsll
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMExJU2gxMWR3d1NNdFdw
        QnZZSnVld3NabVZldVJkTWRZYTV2MkJ6Vm5NCndCRlFWT1lrNTBMNEx1RzJlV0Zt
        S1BJN0U0SVBSM1U3YUEyZHNQUTRnTncKLS0tIENlaFVIL1A1SSsxYWR5aVFHeGVF
        WC9YQTdnRW80VTI3S0p2MXZVRkRZYU0KdHsbWrJjKq/LHTX9wBqCi+sGoptgJKmV
        lLka+4bgkZgJs376blVTes7kcoMKqqgkS8vEN1bYM++pAOM1knOnnw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-18T00:07:32Z"
  mac: ENC[AES256_GCM,data:0jtZXQe7e0AFVliB/eXbAVLN9Y5DVSQ1lUFsWykhmWqIrR3W65dykIfN3kU92kTDEVyHtTjSSh+n/VRETZfW/cmZ8VixyVeby+efQo46H4ejyPVV6nsuoBce2l0WdD6TXOFnQ8r8TXDKC8tH/enGdm1DfoqzEWJha3PzFHzq+w8=,iv:uhD6FA2wW+CZoSXCUudXHjZEiysgt5lJxsHVn0hkJko=,tag:jo6N58dHhv/cWwjU/Gh0sg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
