apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:yP2kTFiKGp8a2WJUAGZBZhTN9SjHMiaqN96oGwhEbkKu7KQO9Nfgs9AzqfcCdmdF6Yxh91qIXS3o3r2Ds0S2QzESji6B4PWuOi8sbKT5SgyFF4FTcPE0iKnNtf76vSB1SAtLPWq3Jusmi7nRXrlE9don/4kauJyt+8qVE+AgausIMIAzSrGb+oaFpqGVAEzC3GEJteYl5lguf50OWJyg04SiaGZ3WByO0nXnJPS/hcqppwyR,iv:XKYhaQ1DQCdte3hTvuLcCUjpvgdbTfL2PcDkGMRz8Bo=,tag:vs/uYkawLSDEOclGAZ55uQ==,type:str]
sops:
  age:
    - recipient: age1g5svy8c3sp3w9xqg7xrq8y3ckk36f7k59f0jgl8wx2vywqz7qpnqm8tsll
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MGRGSUQ4RUc3SlQ4K0JI
        UXB4SVFMTG1CWWxMRnpNeGhQZ3pGdVY4d0NZCkJLNHp5TUJhanhsVnNxaTdYMDQw
        ZmUxNlJwc0U3RS9lK1hGbnBvUHQ1V0EKLS0tIHZYNmZkYkNmeFVsY2l1aXFROE5V
        UGpkTkZ1ODdXbnRmSHpKWVNBbTZXQjgKjYIKllBE0aT+294aZZAx73yXHVl1OJij
        2RY0fgtN414QykL6zFrZzsXEZay2HBKUPSCHh8jz1c0L5RbluRHwKA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-17T23:16:32Z"
  mac: ENC[AES256_GCM,data:/KHFrIzfIlWnju/GNuS/p+scuDFfrW3W/esaD8qnje6yVI1FepSSQihseQWOsAJXRErpdFxwgjP1wYd7jnFG7jOS0g2V1fLsnJae/L9+otGLcPFMg6y/1zUKB6LlHtbKnf4ouse5p5XI+zuC23hMXwn/hWAioBUUnSaStyT1TKs=,iv:igpVnxLZ+bZWxtVYABBR35Ya1mABv6GPktNbR/25n9o=,tag:TPyD8sA/Q6pi3bQFEU+irg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
