---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: rancher
  namespace: flux-system
spec:
  interval: 1h
  url: https://releases.rancher.com/server-charts/latest
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: rancher
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: rancher
        namespace: flux-system
  install:
    createNamespace: true
  targetNamespace: cattle-system
  values:
    hostname: rancher.onmyputer.com  
    replicas: 1
    ingress:
      enabled: true
      ingressClassName: nginx       
    bootstrapPassword: 
      valueFrom:
        secretKeyRef:
          name: rancher-bootstrap-password
          key: bootstrapPassword