---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cilium
  namespace: flux-system
spec:
  interval: 1h
  url: https://helm.cilium.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: cilium
      version: 1.16.2
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  install:
    createNamespace: false
  upgrade:
    remediation:
      retries: 3
  values:
    kubeProxyReplacement: "strict"
    k8sServiceHost: 127.0.0.1
    k8sServicePort: 6443
    loadBalancer:
      algorithm: maglev
      mode: dsr
    ipam:
      mode: kubernetes
    bpf:
      masquerade: true
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
    l2announcements:
      enabled: true
    externalIPs:
      enabled: true
    nodePort:
      enabled: true
