apiVersion: v1
kind: Secret
metadata:
  name: discord-bot-token
type: Opaque
stringData:
  TOKEN: ENC[AES256_GCM,data:/zjotG4/+8eEoFeivkqiUgQugp4OgdK9Xe1CeUaTnnoRTm2JMVwGyVToZebKvu37ZP365yyk/zr0FcAgB5yFeFggq2hcQwpV,iv:CctTsAoANyB2B3qf1LOhNKJvTadv33q+3qunqIsUE7Y=,tag:TaWJ7G6iT2PtDvHAfmgAMg==,type:str]
sops:
  age:
    - recipient: age1g5svy8c3sp3w9xqg7xrq8y3ckk36f7k59f0jgl8wx2vywqz7qpnqm8tsll
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2YUZPZXpuL1N5MEhqKzZL
        QnMyZ0lQMEhFeEs5ZlZpNDh5cVBwUGo3SFVVCk1tNGs1ZXh0SVoxUmlXZmY2Vi8v
        NUlIei9sbVNiancyNTIwbjg5ZlFuTGsKLS0tIGtaclVQZzBiY2tzY25EY1BZVDM3
        aXNHdWp5dTlBcC9DUjAzMTh5Q1MzUEkKyKT230Evy7hRtncD8tvLO7gjPA0UV2o8
        L3t3ogJAYLaJykpUfEKIfVLXr50bpDg1fOTlkERGrXdUCF2YZqwwrw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-06T02:26:41Z"
  mac: ENC[AES256_GCM,data:u+svTuuxHnNTuHvOtM7pTv2Fdb2KaIrDDcRV7ymkEGUjALHh6uJZE0Yp7FCKFyk2YZEywvSAU19sApupExgRRsTBzm06cYTK4tJyu7Lx4dvEQFOMZYbgkXbWoODvg39E8r+jSMeZawjlDgzdHAesN3z2or/38B6M5AOZ8Okivyo=,iv:luyHh1NcOaDm4uqkaJEjE1mhoZzyI/z1B0AyqYT8nxA=,tag:buMeLUaHDR+tge6208bJxg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
