apiVersion: v1
kind: Secret
metadata:
  name: discord-bot-secret
type: Opaque
stringData:
  TOKEN: ENC[AES256_GCM,data:/+YuvX21OXGbtlkS9qOP4B9VMcdBzqWj1ftYPMgnR4MGs46oZFBH226qqV8VoPqrROl5MbWDKNuHETU55Hz09LqsK0cWyaPd,iv:bluzShZaRSNBOsXs6KcuAtuLNiDSqMTZrbdkLFPRmmA=,tag:dznNqr5jNzQi3L3a7KCQwg==,type:str]
  YOUTUBE: ENC[AES256_GCM,data:2ZlW+2EvCNE2yo0MMs3ZErt6K1sFruTrBB7NeNIOyn2qF87ErcBR9KjcS2C1e60wP4cFVSGdZKkz+ozr6sfxoArSfydSYWlz,iv:EBiS3eG36oGG7bmZD+H/IMy2CsBTjnbVT4/I25ilwqM=,tag:Kp0UljD+AItgZAEB/ZCY6A==,type:str]
sops:
  age:
    - recipient: age1g5svy8c3sp3w9xqg7xrq8y3ckk36f7k59f0jgl8wx2vywqz7qpnqm8tsll
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWMjZQOE1GczlNR0o2OTZO
        VFp6QmQ3VlJQRHR4bDRoS0FkQURxeGtZL0g4CmpVWTVKbG43SW5lVnF5R2k5TU4r
        am9OaVNodzZQZHN1ZGtLV1Jjdlo0TDgKLS0tIDlDUUYvUE1BNkFMVXFqVGVoVWdV
        dkN5VzFFcWxMb29iajcydDVaOW9tNzQKFnsuccPPEkgIuepnWpAAFAUJmM2o4v48
        yFoxcYJA9aaEOnsC6tZmAJKZA7KigG+R9MJ/08idcd3VW4aE6EjbbA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-08T03:00:01Z"
  mac: ENC[AES256_GCM,data:H8/PeaYcZ3DwjVmz4tHYehzC0YpkfBfxmNCKkxYzeN6OHcTXAxPkYPKSkRlRJfrjeXkK0LULS1PTdaW8s9RlOJWFeewUYQtQBPMwCHDjQnx6/jwljY5kd6MggEu7SDzdGqftdHRtn8UviIsb1d30GngBEW335cw0AH13aOIROYo=,iv:/nCFz6ddlsUivS3MNbCLAyczXvpR7xzMzYAyLEHad+g=,tag:pfl7d2y+zIgIA1EaU1Imtg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
