apiVersion: v1
kind: Secret
metadata:
  name: discord-bot-secret
type: Opaque
stringData:
  TOKEN: ENC[AES256_GCM,data:wkRP09HRcMCVH+si0x1eMYFWHW5IPkwe7eDcuzS4r8fRgGJ5PSxE8d9bQ3+cZfv8zY/4mOSMFGWkkUa6mROzLnoGSF1W+I94,iv:o9wdY3uiUHRw0DBHlGVIlTlEuPFfdvzY5Q1ZgGHNb9w=,tag:se3/YmCfBIQl/F5ghVMZDw==,type:str]
  YOUTUBE: ENC[AES256_GCM,data:m5KvSHN7js05PCJrRmB2XgxoExsfykH3FT6tUqIg+cIk574AAYR9,iv:Afumcst9YnYwCTlz2UbM0ys6i9BjcqSteC4w8l2X7+M=,tag:hG03VwS7dP/V3byrlbangA==,type:str]
sops:
  age:
    - recipient: age1g5svy8c3sp3w9xqg7xrq8y3ckk36f7k59f0jgl8wx2vywqz7qpnqm8tsll
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFYUw3WVZPK0I3aVFUY1I0
        NVB5VHYvTEI4a3VJamQ1ZEtGUmp3RWtKekJvCitVdFRYdEFncUkvTGRFMGVNMys2
        cWF1MjRXbXBseGFhellQR0tZWk9uT1UKLS0tIEM0VGJVYjVaUTZnOHJLZ2Z5NFk5
        ZFdQRGlkblZPQ1FrTFNGd1NCTHNjdnMK4MLcis4Tjb0/wTPYKCjgRxmtEfzqDyyZ
        UyJOgXXofkrtRUtEjZQEpH8OedJ4YQXOMcj6PZBWqt+/yLSzrctMKg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-08T03:07:19Z"
  mac: ENC[AES256_GCM,data:87TDP2tY1se+JAxeRI+nV+Z/7ogS61T1lhILmKx8N+59wcYokS7H/+EY4FMDdIBU+F5bvdMcx441iSgDizRBSxBv/sUC5tN8XvQwNmKcGLfBc//8EZ8KuFIs5ebNfvZPNRguy2VmSEFIhNnFe1mz/PR8lmyOCLlyFzIBHKsLtkw=,iv:3RGimecIVAwn6jnaMb1MNy9MJrdvGdfpPtNK7+iM+ZI=,tag:0+uGSYYSWIUHsMvt1ZaarQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
