apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:HQYdaHHPa0LTVckmgAhMpfcJwxg8Xe7yttVc255Bik31NFtiaMjl6Q==,iv:PM73wdLAwpDSw93XruFBzJ/VHvOpYZr5Ks+jXF4fDK0=,tag:6EA5Par+TC6r8TYSN2+Fmg==,type:str]
sops:
  age:
    - recipient: age1g5svy8c3sp3w9xqg7xrq8y3ckk36f7k59f0jgl8wx2vywqz7qpnqm8tsll
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvQmQvUnB4SnhieWUya2Qr
        ODF3WFh4WlRubjVobXV1UVpxVGRSZ0Y2a0hRCjR3UHNZTmM4RW84eUJtUHJnZDNU
        UEVTQ2NMaHJTYnBxWGhCRHlkMmdnQmMKLS0tIG5Gem5lb09SSCtZMVRDM0ZNcmt3
        K1k5WEt1ckJNUWozL2tValB6Q2E3clUKcwg0tEQ/goDrhZ4FBZNLrQd+CMbSEhnA
        h3DdEom7CO4fy/A31JlN3XKY410Dn8guf/vSJXJ+f6Wjnssv1OSoWg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-18T00:21:37Z"
  mac: ENC[AES256_GCM,data:XGH7QvLmCTQUOfPNs3W3d8VXV7TzfL/VN2slm1d+5Y2BSHV6g4pWmYbSnTW9lJJx/Bt7Fq2mfVi95Ii+ftXC35Zixek/yuuVWeavkVhEp1IFDPve7boDcaf8f19XxQHozDyTy2YH3rznmRwfGaERHzkZnEvkCugIzQTb3ilHmXc=,iv:AAik4BYDzaP4194PvbeH2vZKbj1nLb08qnp9mMV8Ym4=,tag:QZbTI/sYGXtWU8zfMlMozg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
