apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:TsxqbWzo6UNvVjisZ7aQoQBxdIlgecly7NhPoh4KabDfilbmlY7Ofg==,iv:3vNfZ+NXXAjQZ2v85B2i5q8fU2j8kKhCbw70PhJ5Has=,tag:gplU4DnBrl72cHzR06xkcA==,type:str]
sops:
  age:
    - recipient: age1g5svy8c3sp3w9xqg7xrq8y3ckk36f7k59f0jgl8wx2vywqz7qpnqm8tsll
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqV0F5U0xhSEtvVjhGbktC
        N2ZibFRHOUs2ZXZpZG11R2RFRllUZHEyWG00Ck9nS3FlbHFsSlg5eFFEN2JneFkr
        NjNKSXVkQUR3T0JiL2xNdnMzYWcrR3MKLS0tIGxDbXRObFZ0QWdVWDVaMUl3U25V
        d0lyV2NWOGgzV3VHWFJra3dvelk2RFUKG54JH21fA8rfchT5n1ZRA8JQbc+aGukf
        qYXSjGwSqnCqWgVzoXSnvgyR2Sd68COtCNKBNOWfkSCUOG/LN1MX6Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-18T00:07:32Z"
  mac: ENC[AES256_GCM,data:1fq9bxhofT/IRRk0FEdS86te4ZjsaOFV3RMleCxBNlRzJbbscXMObSTAFK0Bj+EVMXOdmmOPR0mtMw9BtL569WVktATUx6PesG7clIpHgP17A0jyVngxkhRfjxsNbuJhjZ6NcFDkceWSb4W2AAORj4q0SbsAC+9++L0+5ndy7AM=,iv:IVJfTxbn1qHaiJtmgiBuwDDUNwABivN6bIM2IGAUH+k=,tag:jvvVcuQXhZ4NHddB3AvEYA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
