apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:kylxvYynS8yBEq0Qe4CB8KxbbKBgNHvNgmNJSbHPC93YYMJg1BkCew==,iv:vdvfnTGHkagh1haGzMokg38iNu7uMSbkhX9rH8GDgyI=,tag:Vy9mqz6KpcYCZSJLKK0EGA==,type:str]
sops:
  age:
    - recipient: age1g5svy8c3sp3w9xqg7xrq8y3ckk36f7k59f0jgl8wx2vywqz7qpnqm8tsll
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvUVdjMVJnZkpTbGhGZTg2
        U05ZKy96cEpnQUVNbVdhSHZ0Y2U4Qk81TjJzCnQyQnJPNjlzU2RObmxiN2xmTm9y
        aG93Y21YVjhQYVNmZ0gvNnpGVG5NNmMKLS0tIEVoLzZIVVZKd1UrWlFDbEJ0SUZR
        RElTV3E5Q2xXbHYxQkRMUXFSM1YxelUKRAjRaHLywFCCoasilMtbjCWch9FIQpqm
        mT29nV2x5nWRkCTM+6z+UbUKWMxTcFmcHL/3w6NXOXKEJdt6imAf9Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-18T00:02:22Z"
  mac: ENC[AES256_GCM,data:0E7LOiOSWg0kVqdZTHeKK/88xp9ZXH4kOGU/UVvQE2ryTGZ+CWGtYe1lCTPi1XaTfKoaO4HyWzaYS/SCo/J7u0Iqoo6AQI1bb6plwTaG3uzCDL38cWUM8sifgfY/OnnNXjJkNQpLfIOPpMy4DSYX+0Yp2aLQoTeghpHlPqtX0UE=,iv:SrjkK6zzZ47lIfrvUwjLXGcqaAu7gwUAIYASvTAN4zE=,tag:Kub3o3UvoDVOITMpTs2UpQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
