---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBQIsFVE2xdHlXAbhsdMfljj/U8IVcQJ4Wo14611tKV1WCOKO5VwXcgHfjkeif1ZzmNBSC9H8Rh7rMbKbTIeA96s9wncyILB1NeOtfAUokZfO2boU0LBPpoZaQog7lKaZmsMexNuAYPCYTqnDB7xtucBeo6oh8jL53Zs4MvYRtU+Z3CU98LtCfFs9Ja5vPePzUKL24Jm/hQdGKnfBJFdVyX6bCxHEDaiKDjm6n+10nOV+dqY/cveXIK7MzmiCiFqUwxgu/NSwvnWLnmtDevsxyy1R7v0G1pJ3Ns84UB4zi6rpVOFHl32/qW9fd1laXFS8bFYaue01GLkoGuxIA/PJa/cskZdXoPqgfSPl4+24qa+cMqKg6ygs9Z5BO/GJgaQoiRi7rHAWZMxDwuHRLQxuWopu6uJx4fHZTF/s2oGcp6TsR+zfZ4AJ+8cf7cBACLHLA1doLb3rMqf6epsjlRBWTInBtF2m2kXlcyeD+yoDEw2ffaKFGSyl6HoFr9rbWZ5sU0Fi1zh97tryjatT8NfaUksauVJ9Nam19vvYnowSgUbB7mjR9JMzEsqcNYUFRWhs5FN+g1NL3ZUScH9PDVbatR2y37kxRmVTloC12gwoT9vdg+R96vjQmi1Fg/9J2ibSVYSbDNKSmkkui/ijzRXrUjeIzAfndNxAUpfG/Ly56JGytnacueKaysnLMuAYKo1DH5dXpQCMPl2U6+qudX2zcjKf6FfPz3i0NauXBIPr91n+XvVwmoENhm
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
