apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rancher
  namespace: cattle-system
spec:
  ingressClassName: nginx
  rules:
  - host: rancher.onmyputer.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cattle-system-rancher
            port:
              number: 80
  tls:
  - hosts:
    - rancher.onmyputer.com
    secretName: tls-rancher
