apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radar
spec:
  chart:
    spec:
      chart: radar
      sourceRef:
        kind: HelmRepository
        name: skyhook
        namespace: flux-system
  interval: 1h
  values:
    replicaCount: 1
    image:
      repository: ghcr.io/skyhook-io/radar
      pullPolicy: IfNotPresent
      tag: ""
    rbac:
      create: true
      additionalRules:
        - apiGroups: [""]
          resources: ["namespaces"]
          verbs: ["get", "list", "watch"]
      helm: false
      secrets: false
      viewRBAC: false
      podExec: false
      podLogs: true
      portForward: false
      selfUpgrade: false
      traffic: true
      crdGroups:
        argo: true
        certManager: true
        contour: true
        crossplane: true
        externalSecrets: true
        flux: true
        gatewayApi: true
        istio: true
        karpenter: true
        keda: true
        knative: true
        kyverno: true
        prometheus: true
        traefik: true
        verticalPodAutoscaler: true
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 65532
      runAsGroup: 65532
      fsGroup: 65532
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 65532
      capabilities:
        drop:
          - ALL
    service:
      type: ClusterIP
      port: 9280

    route:
      app:
        hostnames: ["radar.onmyputer.com"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: 9280