---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator
spec:
  chartRef:
    kind: OCIRepository
    name: flux-operator
  interval: 1h
  values:
    serviceMonitor:
      create: true
    service:
      app:
        ports:
          http:
            port: &port 9080
    route:
      app:
        hostnames: ["{{ .Release.Name }}.onmyputer.com"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port