---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  chartRef:
    kind: OCIRepository
    name: home-assistant
  interval: 1h
  values:
    controllers:
      home-assistant:
        replicas: 1
        strategy: Recreate
        containers:
          app:
            image:
              repository: ghcr.io/home-assistant/home-assistant
              tag: latest
            env:
              HTTP_PORT: &port 8123
              TZ: UTC
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 50m
                memory: 2Gi
              limits:
                cpu: 500m
                memory: 4Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
    service:
      app:
        ports:
          http:
            port: 8123
    route:
      app:
        hostnames: ["{{ .Release.Name }}.onmyputer.com"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      data:
        type: persistentVolumeClaim
        persistentVolumeClaim:
          claimName: home-assistant-config
        globalMounts:
          - path: /config